baseURL = 'https://trinitui.github.io/electrostate_files/'
languageCode = 'en-us'
title = 'The Electrostate'

theme = 'hugo-bearcub'

[params]
  [params.author]
    name = 'The Electrostate'

[caches]
  [caches.images]
    dir = ':cacheDir/images'